theme = "x"
# inherits = "theme_name"
# "ui.background" = { }
# "ui.cursor.primary.normal" = { modifiers = ["reversed"] }

[editor]
scrolloff = 7
mouse = false
auto-info = true
true-color = true
color-modes = true
line-number = "relative"
bufferline = "multiple"
# end-of-line-diagnostics = "hint"
jump-label-alphabet = "asdfghjkl;"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"
separator = "│"
left = [
  "read-only-indicator",
  "mode",
  "spinner",
  "version-control",
  "spinner",
  "diagnostics",
]
center = [
  "spacer",
  "spacer",
  "spacer",
  "file-base-name",
  "file-encoding",
  "file-modification-indicator",
]
right = [
  "register",
  "separator",
  "file-type",
  "separator",
  "selections",
  "separator",
  "primary-selection-length",
  "separator",
  "position",
]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true
character = "▏"

[editor.soft-wrap]
enable = true

[keys.normal]
"," = "no_op"
";" = "@miw"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.S-tab]
Q = ":qa!"
Z = ":xa!"
R = ":config-reload"
r = ":redraw"
b = ":toggle-option bufferline never multiple"
w = ":toggle-option soft-wrap.enable"
i = ":toggle-option indent-guides.render"
p = ":sh pv \"$(ls *.tex)\""
"\\" = ":toggle-option whitespace.render none all"
